### ISSUE TITLE
Questions about the templates

### ISSUE THREAD

**Issue by etifontaine** [redirectionio/kubernetes-example#1]
Hello!
I have some questions regarding the example provided here:

- Why do we need a PVC, and how can we size it regarding our usage, what is stored in it ?
- Can the agent and the proxy run with multiple replicas?
- You specify, `Recreate` as strategy in the Deployment, what the limitation about not using strategy? 

Thank you!

**Comment by joelwurtz** [comment]
Hey,

> Why do we need a PVC, and how can we size it regarding our usage, what is stored in it ?

It is used to store a local cache of the rules from our Saas, which will be used for fast / fresh start (before the first http request) and in case of failure from our platform so you always have the last ruleset available even if we are down.

But it's not mandatory, agent can work fine without it, it's just recommended for better availability

About the size, for a very large plan it can go up to 100Mb, but should never be higher than that, it's generally between 1Mb and 10Mb 

> Can the agent and the proxy run with multiple replicas?

Yes they can, proxy request to the agent are stateless, so you can have a tcp loadbalancer strategy between them, there is no limit to the number of agent or proxy

> You specify, Recreate as strategy in the Deployment, what the limitation about not using strategy?

None, this is an error, we should keep the default here (rolling update) (all strategies should work)

**Comment by etifontaine** [comment]
Thank you for the fast answer!

**Comment by etifontaine** [comment]
Hey,

What would you use for the `livenessProbe` and `readinessProbe` ?

Plus, it seems that when I deploy a new pod of the agent, I need to rollout restart the proxy, is that a normal behaviour regarding the Nginx?

Thank you

**Comment by joelwurtz** [comment]
Hello,

> What would you use for the livenessProbe and readinessProbe ?

We do not provide any endpoint for those probe ATM, but agent should be ready once it's port is available, and you can check that the port is available for liveness also, all request are stateless, so even if one failed it should not impact other request

> Plus, it seems that when I deploy a new pod of the agent, I need to rollout restart the proxy, is that a normal behaviour regarding the Nginx?

Nginx will use persistent connections between him and the agent with a pool of connections in order to avoid a tcp connect workflow for each request, it remove them / invalidate them if there was a connection error (or if there is more connections than authorized given the pool configuration)

If you have a direct link between nginx and the agent there may be bad connection keeped when deploying a new pod (since old connections are keep)

I'm not sure how does the kubernetes service handle this problem, if it keep the link or does a hot update ? Can you try to use a StatefulSet instead of a Deployment for the agent maybe it will be better ?

To be honest we are definitely not expert on kubernetes but we are slowly gaining knowledge on it  as we want to update some of our internal service to k8s; There will be update to the agent in the next month to have a better integration (readiness / liveness / prometheus metrics / etc ....) and maybe an integration with ingress controller, our goal will be to have a helm chart for the agent / proxy system but we have no official ETA for those features.
